identified sub-objects and what they can do
ChrisNewmanGDL/PFMCPP_Project3 pull request #1
Opened 2021-06-18 11:31 UTC by ChrisNewmanGDL

2021-06-18 20:52 UTC, matkatmusic approved these changes

2021-06-19 00:03 UTC, matkatmusic approved these changes

2021-06-19 20:08 UTC, matkatmusic approved these changes

2021-06-19 21:54 UTC, matkatmusic approved these changes

2021-06-21 07:59 UTC, matkatmusic requested changes
Lots to do!!
But it's mostly 2-3 major things that need fixing, that were done in each UDT.

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    float adminCostTotal;
Provide some default values for your member variables
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    };
Nested types need to have 5 properties and 3 actions. 
you have 3 properties and 0 actions
Also, this indentation needs fixing
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    };
This indentation needs fixing
you need to add some default values to these member variables.
you have a function parameter with a name that doesn't conform to the coding standard.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    void selectOscWaveform (int WaveformControlPosition, float waveformModInputVolts);
your first parameter's name does not conform with the coding style for variable names.
the first character of a variable's name should be lower case.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    int modulateArpMode(int ModeControlValue, float modeModulationInputVolts);
you have a function parameter with a name that doesn't conform to the coding standard.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    float clockInputVolts;
this is missing a default value
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    int modulateSeqLength(int SeqControlValue, int seqLengthInputVolts);
you have a function parameter with a name that doesn't conform to the coding standard.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    bool IsHighPass = true;
you have a member variable with a name that doesn't conform to the coding standard.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    void selectOscWaveform (int WaveformControlPosition, float waveformModInputVolts);
you have a function parameter with a name that doesn't conform to the coding standard.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    int waveformControlPosition;
this variable needs a default value
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +};
This struct is not indented correctly. 
Always strive to make your code look as good as possible, starting with correctly indenting everything.
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +};
This struct is not indented correctly
please see the Coding standard in the Readme.MD for what indentation settings you should use in Replit and re-indent this UDT
- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    float payAssessor(Assessor assessorName, Assessor accountNumber,float assessorHoursSpent, int travelTime);
2 things:
1) When you have functions with lots of function arguments, you can improve the readability if you put each argument on its own line:
```
float invoiceReport(Assesssor assessorName,
                    float chargeOutRate,
                    float assessorHoursSpent,
                    float supervisionHours,
```
2) 
> When you pass this `Assessor` type into this function, the instance that is used inside this function is NOT the same instance that was passed in.
> That means any changes you make to the instance being used INSIDE the function are NOT kept when this function ends.
> the C++ concept of References and Pointers has not been covered at this point in the course.  If you wanted this to work as you are most likely expecting it to work, you would need to use references or pointers.
> I don't let people use coding concepts in projects until after they've been covered in the course.
> You don't need to revise these function parameters
> I just want you to be aware of the potential issue.
> This is a common issue with new programmers or programmers who are coming from garbage-collected languages (python, C#)

- [ ] revise

2021-06-21 07:59 UTC, matkatmusic commented on main.cpp
> +    //3) increase cut off frequency
You have not declared 3 functions that match these 3 plain-english actions.
however, you have declared 3 functions correctly that are relevant to this `Synthesizer` type.
Either change your 3 plain-english actions to match your functions, or change your functions to match these 3 plain-english actions.
- [ ] revise

2021-06-21 19:06 UTC, ChrisNewmanGDL commented on main.cpp
> +    float payAssessor(Assessor assessorName, Assessor accountNumber,float assessorHoursSpent, int travelTime);
Aha! I know I haven't got my head around this idea. I've watched a few videos on pointers and references but never quite got it. It will be good to get a chance to learn about this in the context of a particular task when we get there.

2021-06-22 21:27 UTC, matkatmusic approved these changes

2021-06-22 21:27 UTC, merged