functions with while and for loops, modifying objects created outside…
ChrisNewmanGDL/PFMCPP_Project3 pull request #5
Opened 2021-07-19 07:22 UTC by ChrisNewmanGDL

… the loop

2021-07-19 07:43 UTC, matkatmusic requested changes
In addition to all of the stuff I marked below, you need to fix the inconsistent spacing around `(`.
Consult the `readme.md` to learn what I'm expecting to see regarding the spacing around `(`
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
>      }
Fix this indentation
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
> +
- Indentation needs fixing
- add space around `=` to improve readability
- prefer the use of pre-increment over post-increment. 
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
> +    Arpeggiator(int n):arpLength(n) {}
add space around the `:` to improve readability
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
> +    }
Fix this indentation
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
> +//    Sequencer rangeSemitones;
Don't remove these member variables.
- [ ] revise

2021-07-19 07:43 UTC, matkatmusic commented on main.cpp
> +    {
add space around the `<` to improve readability
- [ ] revise

2021-07-19 15:05 UTC, ChrisNewmanGDL commented on main.cpp
> +    }
not sure about this indenting

2021-07-19 18:01 UTC, matkatmusic requested changes
When I previously said that you need to fix the spacing around `(`, I was referring to function calls. 
This is incorrect:
```
void someFunc (float arg);
```
This is correct:
```
void someFunc(float arg);
```

When using parentheses in expressions, you need to add spaces to make the code readable.
this is incorrect:
```
std::cout << "Pulse width = " <<(lfoPulseWidthPercent) << "%" << std::endl;
```
the `<<(` is difficult to read.
This is correct:
```
std::cout << "Pulse width = " << (lfoPulseWidthPercent) << "%" << std::endl;
```
Notice that the space around the `(` and `<<` makes the code easy to read.
Furthermore, you do not need to put `lfoPulseWidthPercent` in parentheses.

There are lots of spots in the code where you have decided to wrap expressions in `()` and it is not needed.  

Here is what you need to do: 
- go through the code and fix all of the FIXMEs I have left. 
- each FIXME has been added on a line that either has a formatting error or unnecessary parentheses.

2021-07-19 18:01 UTC, matkatmusic commented on main.cpp
> +//    Sequencer rangeSemitones;
You did not restore this as I specified.
- [x] UNCOMMENT THESE LINES OF CODE.  - OK done that

2021-07-19 18:01 UTC, matkatmusic commented on main.cpp
> +    {
Indent this line correctly.
- [ ] revise

2021-07-19 18:01 UTC, matkatmusic commented on main.cpp
> +            return arpeggiator;
indent this return statement correctly
- [ ] revise

2021-07-19 18:01 UTC, matkatmusic commented on main.cpp
> +        {
Indent that `int` variable declaration correctly
line up your curly braces for this switch statement
- [ ] revise

2021-07-20 19:20 UTC, matkatmusic approved these changes

2021-07-20 19:20 UTC, merged